name: Deploy React App
on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 소스 코드 체크아웃
      - name: Checkout source code
        uses: actions/checkout@v3

      # 2. Node.js 환경 설정
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Node Modules 캐싱
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      # 4. 의존성 설치 및 프로덕션 빌드
      - name: Install dependencies and build (Production)
        run: |
          npm install
          CI=false npm run build:prod

      # 5. GitHub Pages에 배포
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages # gh-pages에 빌드 파일이 올라가도록 직접 설정

      # 6. 이메일 알림
      # - name: Send Email Notification
      #   uses: dawidd6/action-send-mail@v3
      #   with:
      #     server_address: smtp.gmail.com
      #     server_port: 587
 
      #     subject: "React Build and Deploy Complete"
      #     body: |
      #       netflix-demo 레파지토리의 Git action이 작동했습니다.
